### ISSUE TITLE
Empty awards list

### ISSUE THREAD

**Issue by dfcreative** [JaredCubilla/jsonresume-theme-classy#4]
Hi @JaredCubilla !
If I have `awards:[]` in my resume the template gives 
```html
TypeError: Cannot read property 'title' of undefined
    at Object.render (/home/ubuntu/theme-manager/themes/jsonresume-theme-classy/1.0.9/index.js:265:29)
    at /home/ubuntu/theme-manager/lib/theme.js:23:43
    at tryCatcher (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/theme-manager/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by tomaszkrzyzek** [comment]
+1, in my case the theme doesn't seem to be working at all, I just keep getting this error.
